=== giellalt/dict-fin-smn/dtd/finsmn.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( fin ) #IMPLIED
>
<!ATTLIST r
      id ( finsmn ) #IMPLIED >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>


<!ELEMENT e (lg, mg+, ig* ) >
<!ATTLIST e
      src CDATA #IMPLIED
      id CDATA #IMPLIED
>
<!ELEMENT lg (l+, l_ref*, algu?) >
<!ELEMENT l (#PCDATA) >
<!ATTLIST l
      pos ( A | Adv | CC | CS | Pcle | Po | Pron |
            Interj | N | Num | Phrase | V  ) #REQUIRED
      attr CDATA #IMPLIED
      sci  CDATA #IMPLIED
      type ( Prop ) #IMPLIED
      r1_par CDATA #IMPLIED
      r2_par CDATA #IMPLIED
>
<!ATTLIST l t_type ( Phrase ) #IMPLIED  > <!-- fix -->
<!ATTLIST l comma CDATA #IMPLIED >
<!ATTLIST l syn CDATA #IMPLIED >
<!ATTLIST l sem_type ( Plc ) #IMPLIED >
<!ATTLIST l re CDATA #IMPLIED >
<!ATTLIST l tt CDATA #IMPLIED >


<!-- algu = lemma IDs in the algu database -->
<!ELEMENT algu EMPTY >
<!ATTLIST algu lekseemi_id CDATA #REQUIRED >
<!ATTLIST algu sanue_id CDATA #REQUIRED >



<!ELEMENT mg (semantics?, l_ref?, dg?, tg+, xg* ) >
<!ATTLIST mg
      xml:lang ( smn ) #IMPLIED
      rest CDATA #IMPLIED
>
<!ATTLIST mg id CDATA #IMPLIED >
<!ATTLIST mg src CDATA #IMPLIED >


<!-- definition  -->
<!ELEMENT dg ( re?, d, dt? ) >
<!ELEMENT d (#PCDATA) >
<!ELEMENT dt (#PCDATA) >


<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >


<!ELEMENT tg (semantics?,  ( ((re?, t+, stem*, l_ref?) ))+, xg*, syng?) >
<!ATTLIST tg
      xml:lang ( smn ) #REQUIRED
      check CDATA #IMPLIED
      tw_id CDATA #IMPLIED

>
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ATTLIST re
    xml:lang ( fin | lat) #IMPLIED
>

<!ELEMENT t (#PCDATA) >
<!ATTLIST t t_type ( Pers | expl | Phrase ) #IMPLIED  >
<!ATTLIST t pos ( A | Adv | CC | CS | Interj | 
            N  | Num | Pcle | Pr | Pron | Po | 
            V | X ) #IMPLIED >
<!ATTLIST t type ( expl
                  | grammarexpl |Prop | Indef | G3 | NomAg | Coll | Recipr | Pers
                  | grammar | Refl | Dem | Poss | Logo | Rel | Interr | TV | IV ) #IMPLIED >
<!ATTLIST t src CDATA #IMPLIED >
<!ATTLIST t l_par CDATA #IMPLIED >
<!ATTLIST t wf CDATA #IMPLIED >
<!ATTLIST t t_tld CDATA #IMPLIED >
<!ATTLIST t syn_dash CDATA #IMPLIED >
<!ATTLIST t attr CDATA #IMPLIED >
<!ATTLIST t r_par CDATA #IMPLIED >
<!ATTLIST t mwe CDATA #IMPLIED >
<!ATTLIST t syn CDATA #IMPLIED >
<!ATTLIST t hid CDATA #IMPLIED >
<!ATTLIST t xxx CDATA #IMPLIED >


<!ELEMENT xg ((x, xt+)+)>
<!ELEMENT x (#PCDATA)>
<!ATTLIST x src CDATA #IMPLIED >
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt src CDATA #IMPLIED >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-fin-smn/src/N_Prop_finsmn.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/finsmn.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="finsmn" xml:lang="fin">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
  <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.
</lic>
<ref>Work by Marja-Liisa Olthuis and Taarna Valtonen, and by Giellatekno at UiT,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref><sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailtofeedback@divvun.no</a> and <a>mailtogiellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote></lics>
   <e src="item">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">itemLabelFi</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">itemLabelSmn</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q258">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Etelä-Afrikka</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Maadâ-Afrik</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q241">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Kuuba</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Kuuba</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q16">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Kanada</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Kanada</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q244">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Barbados</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Barbados</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q17">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Japani</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Jaapaan</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q262">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Algeria</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Algeria</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q265">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Uzbekistan</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Uzbekistan</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q252">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Indonesia</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Indonesia</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q20">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Norja</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Taažâ</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q298">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Chile</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Chile</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q27">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Irlanti</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Irland</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q334">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Singapore</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Singapore</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q28">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Unkari</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Uŋgar</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q347">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Liechtenstein</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Liechtenstein</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q29">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Espanja</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Espanja</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q398">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Bahrain</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Bahrain</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q399">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Armenia</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Armenia</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q30">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Yhdysvallat</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Amerik ovtâstum staatah</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q31">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Belgia</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Belgia</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q403">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Serbia</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Serbia</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q32">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Luxemburg</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Luxemburg</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q33">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Suomi</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Suomâ</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q408">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Australia</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Australia</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q414">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Argentiina</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Argentiina</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q34">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Ruotsi</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Ruotâ</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q419">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Peru</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Peru</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q36">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Puola</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Puola</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q423">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Korean demokraattinen kansantasavalta</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Tave-Korea</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q424">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Kambodža</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Kambodža</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q37">
      <lg>
         <l pos="N" type="Prop" sem_type="Plc">Liettua</l>
      </lg>
      <mg>
         <tg xml:lang="smn">
            <t pos="N" type="Prop">Liettua</t>
         </tg>
      </mg>
   </e>
   <e src="http://www.wikidata.org/entity/Q574">
      <lg>
